import io
import json
import time
import urllib.parse
import urllib.request
from pathlib import Path
from PIL import Image

Image.MAX_IMAGE_PIXELS = None

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_FILE = BASE_DIR / "data" / "artworks.json"
MASTERS_DIR = BASE_DIR / "static" / "img" / "masters"
ARTWORKS_DIR = BASE_DIR / "static" / "img" / "artworks"

MASTERS_DIR.mkdir(parents=True, exist_ok=True)
ARTWORKS_DIR.mkdir(parents=True, exist_ok=True)

USER_AGENT = "ClassicArtArchiveBot/2.2 (https://classicartarchive.org; contact: artarchivebusiness@gmail.com)"
HEADERS = {"User-Agent": USER_AGENT}

artworks_31_to_100 = [
    {
        "slug": "judith-slaying-holofernes",
        "title": "Judith Slaying Holofernes",
        "original_title": "Giuditta che decapita Oloferne",
        "artist": "Artemisia Gentileschi",
        "year": "c. 1620",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "199 cm × 162.5 cm",
        "location": "Uffizi Gallery, Florence, Italy",
        "query": "Artemisia Gentileschi Giuditta decapita Oloferne Google Art Project",
        "description": "The biblical heroine Judith, aided by her maid Abra, violently beheads the Assyrian general Holofernes to deliver her besieged city of Bethulia.",
        "analysis": "A ferocious masterpiece of Caravaggesque naturalism, physical power, and dramatic lighting by the preeminent female painter of the Baroque era.",
        "featured": True,
        "instagram_post_caption": "Artemisia Gentileschi's visceral tour de force: Judith Slaying Holofernes.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-fighting-temeraire",
        "title": "The Fighting Temeraire",
        "original_title": "The Fighting Temeraire, tugged to her last berth to be broken up",
        "artist": "J.M.W. Turner",
        "year": "1839",
        "period": "Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "90.7 cm × 121.6 cm",
        "location": "National Gallery, London, United Kingdom",
        "query": "JMW Turner The Fighting Temeraire National Gallery",
        "description": "The heroic 98-gun ship of the line HMS Temeraire is towed down the River Thames by a paddle-wheel steam tug toward its final scrapyard against a fiery sunset.",
        "analysis": "A poignant poetic tribute to the passing of the age of sail into the Industrial Revolution, bathed in Turner's incandescent atmospheric light.",
        "featured": False,
        "instagram_post_caption": "Turner's greatest sunset and tribute to naval history: The Fighting Temeraire.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "water-lilies",
        "title": "Water Lilies",
        "original_title": "Nymphéas",
        "artist": "Claude Monet",
        "year": "1916–1919",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "200 cm × 180 cm",
        "location": "Musée Marmottan Monet, Paris, France",
        "query": "Claude Monet Water Lilies Google Art Project 462014",
        "description": "Part of Monet's legendary cycle capturing the tranquil water lily pond in his gardens at Giverny, dissolving horizon and sky into liquid reflections.",
        "analysis": "Pushed Impressionism to the threshold of Abstract Expressionism through gestural brushwork, saturated purples and emeralds, and infinite spatial depth.",
        "featured": True,
        "instagram_post_caption": "Monet's meditative harmony of light and water: Giverny Water Lilies in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "luncheon-of-the-boating-party",
        "title": "Luncheon of the Boating Party",
        "original_title": "Le Déjeuner des canotiers",
        "artist": "Pierre-Auguste Renoir",
        "year": "1881",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "129.9 cm × 172.7 cm",
        "location": "The Phillips Collection, Washington, D.C., United States",
        "query": "Pierre-Auguste Renoir Le Dejeuner des canotiers",
        "description": "A radiant summer gathering of friends dining and drinking on the balcony of Maison Fournaise along the Seine River in Chatou.",
        "analysis": "Combines figure painting, still life, and landscape with sparkling light reflections, capturing the joyous joie de vivre of late 19th-century Paris.",
        "featured": False,
        "instagram_post_caption": "Renoir's celebration of friendship, wine, and summer sunlight along the Seine.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-hay-wain",
        "title": "The Hay Wain",
        "original_title": "Landscape: Noon (The Hay Wain)",
        "artist": "John Constable",
        "year": "1821",
        "period": "Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "130.2 cm × 185.4 cm",
        "location": "National Gallery, London, United Kingdom",
        "query": "John Constable The Hay Wain 1821",
        "description": "A rural English scene showing three horses pulling a large farm cart across the shallow mill pond on the River Stour near Flatford Mill in Suffolk.",
        "analysis": "Celebrated for its fresh cloudscapes, shimmering moisture, and deep affection for the pastoral British countryside that inspired Delacroix and the Barbizon School.",
        "featured": False,
        "instagram_post_caption": "Constable's pastoral icon of British landscape painting: The Hay Wain.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "whistlers-mother",
        "title": "Whistler's Mother",
        "original_title": "Arrangement in Grey and Black No. 1",
        "artist": "James Abbott McNeill Whistler",
        "year": "1871",
        "period": "Realism",
        "medium": "Oil on canvas",
        "dimensions": "144.3 cm × 162.4 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Whistlers Mother high res",
        "description": "Whistler's famous portrait of his mother, Anna McNeill Whistler, seated in profile against a muted grey wall decorated with Japanese woodblock prints.",
        "analysis": "An austere study in tonal harmony and geometric composition, asserting art as pure aesthetic form over literal narrative sentimentality.",
        "featured": False,
        "instagram_post_caption": "Whistler's Mother: The iconic Victorian study of aesthetic harmony and quiet restraint.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-card-players",
        "title": "The Card Players",
        "original_title": "Les Joueurs de cartes",
        "artist": "Paul Cézanne",
        "year": "1892–1895",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "47.5 cm × 57 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Paul Cezanne Les joueurs de carte The Card Players",
        "description": "Provençal peasants absorbed in a quiet, solemn game of cards at a rustic tavern table, framed by a single wine bottle.",
        "analysis": "Constructs solid monumental forms through architectural planes of color, establishing the essential foundation for 20th-century Cubism.",
        "featured": False,
        "instagram_post_caption": "Cézanne's monumental simplicity and structured color: The Card Players.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "bacchus-and-ariadne",
        "title": "Bacchus and Ariadne",
        "original_title": "Bacco e Arianna",
        "artist": "Titian",
        "year": "1520–1523",
        "period": "Renaissance",
        "medium": "Oil on canvas",
        "dimensions": "176.5 cm × 191 cm",
        "location": "National Gallery, London, United Kingdom",
        "query": "Titian Bacchus and Ariadne",
        "description": "Bacchus, god of wine, leaps dramatically from his cheetah-drawn chariot to rescue and wed the abandoned Cretan princess Ariadne on the island of Naxos.",
        "analysis": "A triumphant masterpiece of the Venetian Renaissance showcasing dazzling lapis lazuli skies, dynamic diagonal motion, and sensory chromatic brilliance.",
        "featured": True,
        "instagram_post_caption": "Titian's mythological burst of movement and color: Bacchus and Ariadne in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-last-supper",
        "title": "The Last Supper",
        "original_title": "Il Cenacolo",
        "artist": "Leonardo da Vinci",
        "year": "1495–1498",
        "period": "High Renaissance",
        "medium": "Tempera and oil on gesso",
        "dimensions": "460 cm × 880 cm",
        "location": "Santa Maria delle Grazie, Milan, Italy",
        "query": "Ultima Cena Da Vinci 5",
        "description": "Leonardo's timeless mural portraying the dramatic moment Christ reveals that one of his twelve disciples will betray him during their final meal.",
        "analysis": "Masterful one-point linear perspective converging upon Christ's head, conveying emotional waves of disbelief, guilt, and sorrow across the apostles.",
        "featured": True,
        "instagram_post_caption": "Leonardo da Vinci's monumental narrative triumph: The Last Supper.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-sleeping-gypsy",
        "title": "The Sleeping Gypsy",
        "original_title": "La Bohémienne endormie",
        "artist": "Henri Rousseau",
        "year": "1897",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "129.5 cm × 200.7 cm",
        "location": "Museum of Modern Art, New York, United States",
        "query": "Henri Rousseau The Sleeping Gypsy MoMA",
        "description": "A poetic, mystical desert tableau of a slumbering woman and a curious lion under the hypnotic illumination of a full moon.",
        "analysis": "A defining pinnacle of Naïve and Primitivist art, celebrating dreamlike serenity, magical realism, and pure imaginative clarity.",
        "featured": False,
        "instagram_post_caption": "Henri Rousseau's dreamscape icon: The Sleeping Gypsy in pristine Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-scream",
        "title": "The Scream",
        "original_title": "Skrik",
        "artist": "Edvard Munch",
        "year": "1893",
        "period": "Expressionism",
        "medium": "Oil, tempera, and pastel on cardboard",
        "dimensions": "91 cm × 73.5 cm",
        "location": "National Gallery, Oslo, Norway",
        "query": "Edvard Munch The Scream National Gallery Oslo",
        "description": "An agonized figure clutching its face against a blood-red Oslofjord sky, visualizing an infinite piercing scream passing through nature.",
        "analysis": "The supreme icon of modern psychological anxiety and existential dread, pioneering early Expressionism through sinuous curvilinear rhythm.",
        "featured": True,
        "instagram_post_caption": "Edvard Munch's universal icon of existential angst: The Scream in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-storm-on-the-sea-of-galilee",
        "title": "The Storm on the Sea of Galilee",
        "original_title": "Christus in de storm op het meer van Galilea",
        "artist": "Rembrandt van Rijn",
        "year": "1633",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "160 cm × 128 cm",
        "location": "Isabella Stewart Gardner Museum, Boston, United States",
        "query": "Rembrandt The Storm on the Sea of Galilee",
        "description": "Rembrandt's only seascape, depicting Jesus calming the churning waters as terrified disciples struggle desperately with a tearing sail.",
        "analysis": "Dramatic Baroque tenebrism balancing mortal panic and divine tranquility, famously stolen in the historic 1990 Gardner Museum heist.",
        "featured": True,
        "instagram_post_caption": "Rembrandt's lost seascape masterpiece: The Storm on the Sea of Galilee.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-kiss-hayez",
        "title": "The Kiss",
        "original_title": "Il bacio",
        "artist": "Francesco Hayez",
        "year": "1859",
        "period": "Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "112 cm × 88 cm",
        "location": "Pinacoteca di Brera, Milan, Italy",
        "query": "Francesco Hayez Il bacio Brera",
        "description": "A passionate, furtive embrace between a young medieval couple on a stone staircase, rich in romantic intensity and patriotic symbolism.",
        "analysis": "The defining icon of Italian Romanticism and the Risorgimento unification movement, noted for its sumptuous shimmering silk textures.",
        "featured": False,
        "instagram_post_caption": "Francesco Hayez's timeless emblem of passion: Il Bacio (The Kiss).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-ambassadors",
        "title": "The Ambassadors",
        "original_title": "Jean de Dinteville and Georges de Selve",
        "artist": "Hans Holbein the Younger",
        "year": "1533",
        "period": "Northern Renaissance",
        "medium": "Oil on oak",
        "dimensions": "207 cm × 209.5 cm",
        "location": "National Gallery, London, United Kingdom",
        "query": "Hans Holbein the Younger The Ambassadors National Gallery",
        "description": "Full-length double portrait of French diplomat Jean de Dinteville and Bishop Georges de Selve surrounded by globes, musical lutes, and scientific instruments.",
        "analysis": "Famous for its extraordinary anamorphic skull memento mori across the foreground, representing the ultimate vanity of earthly knowledge and political power.",
        "featured": True,
        "instagram_post_caption": "Hans Holbein's Northern Renaissance tour de force: The Ambassadors.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-entombment-of-christ",
        "title": "The Entombment of Christ",
        "original_title": "Deposizione",
        "artist": "Caravaggio",
        "year": "1603–1604",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "300 cm × 203 cm",
        "location": "Pinacoteca Vaticana, Vatican City",
        "query": "Caravaggio Deposizione Pinacoteca Vaticana",
        "description": "Nicodemus and Saint John lower Christ's lifeless body toward the tombstone, flanked by the Virgin Mary, Mary Magdalene, and Mary of Clopas.",
        "analysis": "Masterpiece of Italian Baroque naturalism, drawing the viewer directly into the physical mass and solemn weight of grief through stark chiaroscuro.",
        "featured": False,
        "instagram_post_caption": "Caravaggio's theatrical darkness and monumental sorrow: The Entombment of Christ.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "starry-night-over-the-rhone",
        "title": "Starry Night Over the Rhône",
        "original_title": "Nuit étoilée sur le Rhône",
        "artist": "Vincent van Gogh",
        "year": "1888",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "72.5 cm × 92 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Vincent van Gogh Starry Night Over the Rhone Musee dOrsay",
        "description": "Gas lights of Arles cast shimmering golden reflections upon the dark blue waters of the Rhône under the radiant constellation of the Great Bear.",
        "analysis": "Van Gogh's romantic nocturnal meditation on cosmic illumination and peaceful river waters, capturing the night sky with luminous aquamarine harmonies.",
        "featured": True,
        "instagram_post_caption": "Van Gogh's shimmering nocturnal poetry: Starry Night Over the Rhône in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-ninth-wave",
        "title": "The Ninth Wave",
        "original_title": "Девятый вал",
        "artist": "Ivan Aivazovsky",
        "year": "1850",
        "period": "Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "221 cm × 332 cm",
        "location": "State Russian Museum, Saint Petersburg, Russia",
        "query": "Ivan Aivazovsky The Ninth Wave Russian Museum",
        "description": "Shipwrecked sailors cling desperately to a floating mast amidst colossal oceanic swells, illuminated by the warm, transcendent rays of the morning sunrise.",
        "analysis": "The zenith of Russian marine Romanticism, contrasting the terrifying sublimity of the ocean with the hopeful golden light of survival.",
        "featured": True,
        "instagram_post_caption": "Aivazovsky's oceanic triumph: The Ninth Wave in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-luncheon-on-the-grass",
        "title": "The Luncheon on the Grass",
        "original_title": "Le Déjeuner sur l'herbe",
        "artist": "Édouard Manet",
        "year": "1863",
        "period": "Realism / Early Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "208 cm × 264.5 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Edouard Manet Le Dejeuner sur lherbe Musee dOrsay",
        "description": "A nude female bather sits casually alongside two fully dressed modern Parisian gentlemen in a forest clearing near Argenteuil.",
        "analysis": "Caused an immense public scandal at the Salon des Refusés, breaking free from academic idealism and igniting the birth of modern painting.",
        "featured": False,
        "instagram_post_caption": "Manet's radical revolution of modern art: Le Déjeuner sur l'herbe.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "olympia",
        "title": "Olympia",
        "original_title": "Olympia",
        "artist": "Édouard Manet",
        "year": "1863",
        "period": "Realism",
        "medium": "Oil on canvas",
        "dimensions": "130.5 cm × 190 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Edouard Manet Olympia Musee dOrsay",
        "description": "A reclining courtesan confronts the viewer with an unapologetic, direct gaze as her maid brings a bouquet of flowers from an admirer.",
        "analysis": "Subverted classical Venus iconography with bold flat lighting, tonal contrasts, and unabashed contemporary realism.",
        "featured": False,
        "instagram_post_caption": "Manet's confrontational masterpiece: Olympia in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "a-bar-at-the-folies-bergere",
        "title": "A Bar at the Folies-Bergère",
        "original_title": "Un bar aux Folies Bergère",
        "artist": "Édouard Manet",
        "year": "1882",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "96 cm × 130 cm",
        "location": "Courtauld Gallery, London, United Kingdom",
        "query": "Edouard Manet Un bar aux Folies Bergere Courtauld",
        "description": "A lonely barmaid, Suzon, stands behind a marble counter laden with champagne bottles against a mirror reflecting the vibrant Parisian cabaret crowd.",
        "analysis": "Manet's final masterpiece explores urban alienation, complex spatial perspective, and the glittering ephemerality of Parisian nightlife.",
        "featured": True,
        "instagram_post_caption": "Manet's poignant final monument to Parisian nightlife: A Bar at the Folies-Bergère.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-great-red-dragon",
        "title": "The Great Red Dragon and the Woman Clothed in Sun",
        "original_title": "The Great Red Dragon and the Woman Clothed in Sun",
        "artist": "William Blake",
        "year": "c. 1803–1805",
        "period": "Romanticism / Symbolism",
        "medium": "Black ink and watercolor on paper",
        "dimensions": "43.7 cm × 34.8 cm",
        "location": "Brooklyn Museum, New York, United States",
        "query": "William Blake The Great Red Dragon and the Woman Clothed in Sun",
        "description": "The apocalyptic red dragon from the Book of Revelation flexes massive muscular wings over a celestial pregnant woman clothed in divine light.",
        "analysis": "Blake's visionary mystical imagination at its height, combining muscular anatomical power with cosmic spiritual drama.",
        "featured": False,
        "instagram_post_caption": "William Blake's visionary apocalyptic masterpiece: The Great Red Dragon.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-fall-of-the-rebel-angels",
        "title": "The Fall of the Rebel Angels",
        "original_title": "De val der opstandige engelen",
        "artist": "Pieter Bruegel the Elder",
        "year": "1562",
        "period": "Northern Renaissance",
        "medium": "Oil on oak panel",
        "dimensions": "117 cm × 162 cm",
        "location": "Royal Museums of Fine Arts of Belgium, Brussels",
        "query": "Pieter Bruegel the Elder The Fall of the Rebel Angels Brussels",
        "description": "Archangel Michael in golden armor leads celestial legions to cast hideous chimeric demons and fallen angels down from heaven into the abyss.",
        "analysis": "A dizzying encyclopedic explosion of Boschian monstrosities, hybrid insects, crustaceans, and surreal apocalyptic chaos.",
        "featured": True,
        "instagram_post_caption": "Bruegel's chaotic celestial battle: The Fall of the Rebel Angels in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "hunters-in-the-snow",
        "title": "Hunters in the Snow",
        "original_title": "Jagers in de Sneeuw",
        "artist": "Pieter Bruegel the Elder",
        "year": "1565",
        "period": "Northern Renaissance",
        "medium": "Oil on wood",
        "dimensions": "117 cm × 162 cm",
        "location": "Kunsthistorisches Museum, Vienna, Austria",
        "query": "Pieter Bruegel the Elder Hunters in the Snow Vienna",
        "description": "Weary hunters and their hounds trudge through deep snow overlooking a vast panoramic winter landscape filled with frozen ponds and distant alpine peaks.",
        "analysis": "One of Western art's greatest winter landscapes, celebrated for its exquisite high vantage point, rhythmic diagonals, and atmospheric cold.",
        "featured": True,
        "instagram_post_caption": "Bruegel's winter icon: Hunters in the Snow in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-triumph-of-death",
        "title": "The Triumph of Death",
        "original_title": "El triunfo de la Muerte",
        "artist": "Pieter Bruegel the Elder",
        "year": "c. 1562",
        "period": "Northern Renaissance",
        "medium": "Oil on oak panel",
        "dimensions": "117 cm × 162 cm",
        "location": "Museo del Prado, Madrid, Spain",
        "query": "The Triumph of Death by Pieter Bruegel the Elder Prado",
        "description": "An unstoppable army of skeletons lays waste to humanity across a scorched, burning landscape, sparing neither peasant, soldier, nor king.",
        "analysis": "An unsparing Northern Renaissance memento mori exploring the universality of mortality amidst war and plague.",
        "featured": False,
        "instagram_post_caption": "Bruegel's haunting vision of mortality: The Triumph of Death (Museo del Prado).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "melencolia-i",
        "title": "Melencolia I",
        "original_title": "Melencolia I",
        "artist": "Albrecht Dürer",
        "year": "1514",
        "period": "Northern Renaissance",
        "medium": "Engraving on paper",
        "dimensions": "24 cm × 18.8 cm",
        "location": "Staatliche Kunsthalle Karlsruhe, Germany",
        "query": "Albrecht Durer Melencolia I Google Art Project",
        "description": "A winged personification of Melancholy sits idle amidst scattered geometric, carpentry, and scientific tools alongside a magic square.",
        "analysis": "Dürer's ultimate master engraving (Meisterstich), linking intellectual genius, mathematical order, and spiritual introspection.",
        "featured": False,
        "instagram_post_caption": "Albrecht Dürer's enigmatic intellectual masterpiece: Melencolia I.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "self-portrait-at-twenty-eight",
        "title": "Self-Portrait at Twenty-Eight",
        "original_title": "Selbstbildnis im Pelzrock",
        "artist": "Albrecht Dürer",
        "year": "1500",
        "period": "Northern Renaissance",
        "medium": "Oil on linden panel",
        "dimensions": "67.1 cm × 48.9 cm",
        "location": "Alte Pinakothek, Munich, Germany",
        "query": "Albrecht Durer Self-Portrait Alte Pinakothek Munich",
        "description": "Dürer depicts himself in a fur-trimmed robe in a frontal Christ-like pose with meticulously rendered golden curls against a black background.",
        "analysis": "A revolutionary assertion of the artist as divine creator rather than a mere craftsman, marking the pinnacle of German Renaissance self-portraiture.",
        "featured": True,
        "instagram_post_caption": "Albrecht Dürer's iconic Self-Portrait at 28 (1500) in pristine master scan.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-lacemaker",
        "title": "The Lacemaker",
        "original_title": "La Dentellière",
        "artist": "Johannes Vermeer",
        "year": "c. 1669–1670",
        "period": "Baroque",
        "medium": "Oil on canvas mounted on panel",
        "dimensions": "24.5 cm × 21 cm",
        "location": "Musée du Louvre, Paris, France",
        "query": "Johannes Vermeer The Lacemaker Louvre",
        "description": "A young woman concentrates with microscopic focus on delicate lacework, holding bobbins against a small wooden sewing desk.",
        "analysis": "Vermeer's smallest yet most intensely focused painting, utilizing soft optical blurs and precision to replicate human visual focus.",
        "featured": False,
        "instagram_post_caption": "Vermeer's intimate optical perfection: The Lacemaker (Musée du Louvre).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-astronomer",
        "title": "The Astronomer",
        "original_title": "De astronoom",
        "artist": "Johannes Vermeer",
        "year": "c. 1668",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "51 cm × 45 cm",
        "location": "Musée du Louvre, Paris, France",
        "query": "Johannes Vermeer The Astronomer Louvre",
        "description": "A scholar reaches out to turn a celestial globe by Jodocus Hondius, illuminated by cool Dutch window light beside navigational charts.",
        "analysis": "Celebrates the Dutch Golden Age's scientific curiosity and navigational mastery through warm tapestries and optical precision.",
        "featured": False,
        "instagram_post_caption": "Vermeer's ode to science and discovery: The Astronomer in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "view-of-delft",
        "title": "View of Delft",
        "original_title": "Gezicht op Delft",
        "artist": "Johannes Vermeer",
        "year": "c. 1660–1661",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "96.5 cm × 115.7 cm",
        "location": "Mauritshuis, The Hague, Netherlands",
        "query": "Johannes Vermeer View of Delft Mauritshuis",
        "description": "A tranquil panoramic vista of Vermeer's hometown of Delft reflected across the water under dramatic drifting clouds and golden sunlight.",
        "analysis": "Hailed by Marcel Proust as 'the most beautiful painting in the world,' acclaimed for its pointillist light flecks on red brick facades.",
        "featured": True,
        "instagram_post_caption": "Vermeer's luminous city portrait: View of Delft (Mauritshuis).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-rokeby-venus",
        "title": "The Rokeby Venus",
        "original_title": "La Venus del espejo",
        "artist": "Diego Velázquez",
        "year": "c. 1647–1651",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "122.5 cm × 177 cm",
        "location": "National Gallery, London, United Kingdom",
        "query": "Diego Velazquez Rokeby Venus National Gallery",
        "description": "The goddess of love reclines nude with her back to the viewer, gazing into a mirror held up by her son Cupid.",
        "analysis": "The only surviving female nude by Velázquez, celebrated for its fluid brushwork, sensual elegance, and enigmatic blurred reflection.",
        "featured": True,
        "instagram_post_caption": "Velázquez's sensual masterpiece: The Rokeby Venus in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-surrender-of-breda",
        "title": "The Surrender of Breda",
        "original_title": "La rendición de Breda (Las lanzas)",
        "artist": "Diego Velázquez",
        "year": "1634–1635",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "307.5 cm × 367.5 cm",
        "location": "Museo del Prado, Madrid, Spain",
        "query": "Velazquez La rendicion de Breda Prado",
        "description": "Spanish General Ambrosio Spínola graciously accepts the keys of the Dutch fortress of Breda from Justin of Nassau amidst a forest of upright spears.",
        "analysis": "Celebrated for its magnanimity, psychological warmth, aerial perspective, and majestic composition devoid of cruel triumphalism.",
        "featured": False,
        "instagram_post_caption": "Velázquez's monument of magnanimity: Las Lanzas (The Surrender of Breda).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-clothed-maja",
        "title": "The Clothed Maja",
        "original_title": "La maja vestida",
        "artist": "Francisco de Goya",
        "year": "c. 1800–1805",
        "period": "Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "95 cm × 190 cm",
        "location": "Museo del Prado, Madrid, Spain",
        "query": "Francisco de Goya La maja vestida Prado",
        "description": "A stylish Spanish woman reclines luxuriously on a green velvet sofa dressed in a glowing white gown, yellow bolero jacket, and pink sash.",
        "analysis": "Showcases Goya's bravura impasto technique, vibrant color contrasts, and seductive directness of Spanish portraiture.",
        "featured": False,
        "instagram_post_caption": "Goya's Spanish elegance: La Maja Vestida (Museo del Prado).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-naked-maja",
        "title": "The Naked Maja",
        "original_title": "La maja desnuda",
        "artist": "Francisco de Goya",
        "year": "c. 1797–1800",
        "period": "Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "98 cm × 191 cm",
        "location": "Museo del Prado, Madrid, Spain",
        "query": "Francisco de Goya La maja desnuda Prado",
        "description": "A woman reclines completely nude on pillows, gazing boldly and directly at the viewer with serene confidence.",
        "analysis": "The first major fully secular Western painting to depict female pubic hair without allegorical or mythological disguise, provoking the Spanish Inquisition.",
        "featured": True,
        "instagram_post_caption": "Goya's defiant revolutionary nude: La Maja Desnuda in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-burial-of-the-count-of-orgaz",
        "title": "The Burial of the Count of Orgaz",
        "original_title": "El entierro del conde de Orgaz",
        "artist": "El Greco",
        "year": "1586–1588",
        "period": "Mannerism",
        "medium": "Oil on canvas",
        "dimensions": "480 cm × 360 cm",
        "location": "Church of Santo Tomé, Toledo, Spain",
        "query": "El Greco El entierro del conde de Orgaz Santo Tome",
        "description": "Saint Stephen and Saint Augustine descend miraculously from heaven to bury Don Gonzalo Ruiz of Toledo, while his soul ascends into celestial glory.",
        "analysis": "El Greco's ultimate masterpiece, bridging earthly realism with shimmering spiritual mysticism through elongated figures and incandescent light.",
        "featured": True,
        "instagram_post_caption": "El Greco's spiritual tour de force: The Burial of the Count of Orgaz.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "view-of-toledo",
        "title": "View of Toledo",
        "original_title": "Vista de Toledo",
        "artist": "El Greco",
        "year": "c. 1596–1600",
        "period": "Mannerism",
        "medium": "Oil on canvas",
        "dimensions": "121.3 cm × 108.6 cm",
        "location": "Metropolitan Museum of Art, New York, United States",
        "query": "El Greco View of Toledo Metropolitan Museum of Art",
        "description": "An electrifying stormy landscape of the city of Toledo, crowned by the Alcázar under turbulent rolling midnight-blue clouds.",
        "analysis": "One of the most celebrated landscapes in art history, anticipating Expressionism by three centuries through brooding spiritual intensity.",
        "featured": True,
        "instagram_post_caption": "El Greco's tempestuous vision of Toledo in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-laughing-cavalier",
        "title": "The Laughing Cavalier",
        "original_title": "Portrait of a Man (The Laughing Cavalier)",
        "artist": "Frans Hals",
        "year": "1624",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "83 cm × 67.3 cm",
        "location": "Wallace Collection, London, United Kingdom",
        "query": "Frans Hals The Laughing Cavalier Wallace Collection",
        "description": "A dashing Dutch gentleman in an extravagantly embroidered silk doublet and lace ruff turns with an enigmatic, roguish smirk.",
        "analysis": "Famous for Hals's dazzling spontaneous brushwork that breathes vibrant life, texture, and swagger into the Golden Age portrait.",
        "featured": False,
        "instagram_post_caption": "Frans Hals's swaggering Baroque portrait: The Laughing Cavalier.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-night-cafe",
        "title": "The Night Café",
        "original_title": "Le Café de nuit",
        "artist": "Vincent van Gogh",
        "year": "1888",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "72.4 cm × 92.1 cm",
        "location": "Yale University Art Gallery, New Haven, United States",
        "query": "Vincent van Gogh The Night Cafe Yale University Art Gallery",
        "description": "The interior of the all-night Café de la Gare in Arles with a billiard table, glowing gas lamps, and slumped patrons.",
        "analysis": "Van Gogh used clashing blood reds, toxic greens, and sulphur yellows to express 'the terrible passions of humanity.'",
        "featured": False,
        "instagram_post_caption": "Van Gogh's psychological explosion of color: The Night Café in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "almond-blossoms",
        "title": "Almond Blossoms",
        "original_title": "Amandelbloesem",
        "artist": "Vincent van Gogh",
        "year": "1890",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "73.5 cm × 92 cm",
        "location": "Van Gogh Museum, Amsterdam, Netherlands",
        "query": "Vincent van Gogh Almond Blossoms Van Gogh Museum",
        "description": "Delicate white and pink almond flower blossoms branching against a luminous turquoise sky to celebrate the birth of his nephew Vincent Willem.",
        "analysis": "Deeply influenced by Japanese Ukiyo-e woodblock prints, conveying joyous rebirth, optimism, and emotional tenderness.",
        "featured": True,
        "instagram_post_caption": "Van Gogh's tender masterpiece of hope and new life: Almond Blossoms.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "sunflowers",
        "title": "Sunflowers",
        "original_title": "Zonnebloemen",
        "artist": "Vincent van Gogh",
        "year": "1888",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "92.1 cm × 73 cm",
        "location": "National Gallery, London, United Kingdom",
        "query": "Vincent van Gogh Sunflowers National Gallery London",
        "description": "A rustic yellow vase bursting with fifteen sunflowers in various stages of bloom against a shimmering golden background.",
        "analysis": "A symphony of yellow and orange tones demonstrating that subtle chromatic modulations could convey profound emotional warmth and friendship.",
        "featured": True,
        "instagram_post_caption": "Van Gogh's iconic symphony of golden light: Sunflowers in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "wheatfield-with-crows",
        "title": "Wheatfield with Crows",
        "original_title": "Korenveld met kraaien",
        "artist": "Vincent van Gogh",
        "year": "1890",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "50.5 cm × 103 cm",
        "location": "Van Gogh Museum, Amsterdam, Netherlands",
        "query": "Vincent van Gogh Wheatfield with Crows Van Gogh Museum",
        "description": "A turbulent dark blue sky heavy with gathering storm clouds over golden wheatfields cut by divergent dirt paths and swirling black crows.",
        "analysis": "Painted in Auvers-sur-Oise shortly before his death, expressing immense sadness and extreme solitude through frantic impasto.",
        "featured": True,
        "instagram_post_caption": "Van Gogh's emotional final tempest: Wheatfield with Crows.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-bedroom",
        "title": "The Bedroom in Arles",
        "original_title": "La Chambre à Arles",
        "artist": "Vincent van Gogh",
        "year": "1888",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "72 cm × 90 cm",
        "location": "Van Gogh Museum, Amsterdam, Netherlands",
        "query": "Vincent van Gogh The Bedroom Van Gogh Museum",
        "description": "Van Gogh's simple bedroom in the Yellow House at Arles, featuring pine furniture, lilac walls, red floor tiles, and artwork hung on the wall.",
        "analysis": "Intended to evoke absolute rest and peace through flattened perspective and bold, harmonious fields of color.",
        "featured": False,
        "instagram_post_caption": "Van Gogh's intimate sanctuary of color: The Bedroom in Arles.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "boulevard-montmartre-spring",
        "title": "Boulevard Montmartre, Spring",
        "original_title": "Le Boulevard de Montmartre, Matinée de Printemps",
        "artist": "Camille Pissarro",
        "year": "1897",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "65 cm × 81 cm",
        "location": "Private Collection / On loan to National Gallery",
        "query": "Camille Pissarro Boulevard Montmartre Spring Morning",
        "description": "A bustling Parisian grand boulevard viewed from an elevated hotel room window, alive with horse carriages, pedestrians, and springtime trees.",
        "analysis": "Pissarro captures the fleeting kinetic energy, modern infrastructure, and atmospheric morning haze of Baron Haussmann's Paris.",
        "featured": False,
        "instagram_post_caption": "Pissarro's sparkling Parisian morning: Boulevard Montmartre in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "dance-at-le-moulin-de-la-galette",
        "title": "Bal du moulin de la Galette",
        "original_title": "Bal du moulin de la Galette",
        "artist": "Pierre-Auguste Renoir",
        "year": "1876",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "131 cm × 175 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Pierre-Auguste Renoir Bal du moulin de la Galette Musee dOrsay",
        "description": "Crowds of joyful working-class Parisians dancing, drinking, and chatting in the dappled afternoon sunlight under the acacia trees of Montmartre.",
        "analysis": "A crowning glory of Impressionism, celebrating dappled light filters, movement, and the blissful social vivacity of 19th-century Paris.",
        "featured": True,
        "instagram_post_caption": "Renoir's celebration of light and joy: Bal du moulin de la Galette.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-large-bathers",
        "title": "The Large Bathers",
        "original_title": "Les Grandes Baigneuses",
        "artist": "Paul Cézanne",
        "year": "1898–1905",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "210.5 cm × 250.8 cm",
        "location": "Philadelphia Museum of Art, United States",
        "query": "Paul Cezanne The Large Bathers Philadelphia Museum of Art",
        "description": "Monumental female nudes arranged in a cathedral-like arch of leaning trees beside a calm river.",
        "analysis": "Cézanne's monumental synthesis of classical harmony and structural modernism, directly inspiring Picasso and Matisse.",
        "featured": False,
        "instagram_post_caption": "Cézanne's monumental arch of modernism: The Large Bathers.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "mont-sainte-victoire",
        "title": "Mont Sainte-Victoire",
        "original_title": "La Montagne Sainte-Victoire",
        "artist": "Paul Cézanne",
        "year": "c. 1902–1904",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "73 cm × 91.9 cm",
        "location": "Philadelphia Museum of Art, United States",
        "query": "Paul Cezanne Mont Sainte-Victoire Philadelphia Museum of Art",
        "description": "The limestone ridge of Mont Sainte-Victoire rising above the lush green and ochre plains of Aix-en-Provence.",
        "analysis": "Constructs solid landscapes from rhythmic geometric facets of pure color, bridging Impressionism with early Cubism.",
        "featured": False,
        "instagram_post_caption": "Cézanne's iconic Provencal mountain: Mont Sainte-Victoire in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "where-do-we-come-from",
        "title": "Where Do We Come From? What Are We? Where Are We Going?",
        "original_title": "D'où venons-nous ? Que sommes-nous ? Où allons-nous ?",
        "artist": "Paul Gauguin",
        "year": "1897–1898",
        "period": "Post-Impressionism / Symbolism",
        "medium": "Oil on canvas",
        "dimensions": "139 cm × 375 cm",
        "location": "Museum of Fine Arts, Boston, United States",
        "query": "Paul Gauguin Where Do We Come From Boston",
        "description": "A monumental allegorical frieze created in Tahiti tracing the cycle of human existence from infancy to old age under the gaze of a blue deity.",
        "analysis": "Gauguin's philosophical testament on human destiny, uniting Polynesian mythology with European Symbolist mystery.",
        "featured": True,
        "instagram_post_caption": "Gauguin's grand spiritual testament from Tahiti in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "at-the-moulin-rouge",
        "title": "At the Moulin Rouge",
        "original_title": "Au Moulin Rouge",
        "artist": "Henri de Toulouse-Lautrec",
        "year": "1892–1895",
        "period": "Post-Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "123 cm × 140 cm",
        "location": "Art Institute of Chicago, United States",
        "query": "Henri de Toulouse-Lautrec At the Moulin Rouge Art Institute of Chicago",
        "description": "A group of Parisian bohemians seated around a table at the Moulin Rouge nightclub, with the eerie green-lit face of dancer May Milton in the foreground.",
        "analysis": "Unflinching, satirical chronicle of the Belle Époque nightlife with shocking theatrical acid greens and bold Japanese diagonals.",
        "featured": False,
        "instagram_post_caption": "Toulouse-Lautrec's unforgettable Belle Époque nocturne: At the Moulin Rouge.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-dance-class",
        "title": "The Dance Class",
        "original_title": "La Classe de danse",
        "artist": "Edgar Degas",
        "year": "1874",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "85 cm × 75 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Edgar Degas The Dance Class Musee dOrsay",
        "description": "Ballet master Jules Perrot conducts a rehearsal in the Paris Opera rehearsal hall surrounded by exhausted young ballerinas adjusting their tutus.",
        "analysis": "Degas captures unposed, spontaneous human movement through an asymmetric photographic diagonal composition and exquisite pastel tonalities.",
        "featured": True,
        "instagram_post_caption": "Degas's ballet mastery: The Dance Class (Musée d'Orsay) in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-absinthe-drinker",
        "title": "L'Absinthe",
        "original_title": "Dans un café (L'Absinthe)",
        "artist": "Edgar Degas",
        "year": "1875–1876",
        "period": "Impressionism / Realism",
        "medium": "Oil on canvas",
        "dimensions": "92 cm × 68.5 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Edgar Degas LAbsinthe Musee dOrsay",
        "description": "An actress and an artist sit side by side in the Café de la Nouvelle Athènes in Paris, lost in solemn, vacant alcoholic desolation.",
        "analysis": "A haunting psychological study of urban isolation and addiction in the modern metropolis, framed by a steep zigzag perspective.",
        "featured": False,
        "instagram_post_caption": "Degas's chilling portrait of urban solitude: L'Absinthe in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-cradle",
        "title": "The Cradle",
        "original_title": "Le Berceau",
        "artist": "Berthe Morisot",
        "year": "1872",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "56 cm × 46 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Berthe Morisot The Cradle Musee dOrsay",
        "description": "Morisot's sister Edma watches lovingly over her sleeping infant daughter Blanche behind delicate translucent white netting.",
        "analysis": "The first masterpiece of maternal intimacy exhibited at the First Impressionist Exhibition of 1874, celebrated for its silvery harmonies and tender gaze.",
        "featured": False,
        "instagram_post_caption": "Berthe Morisot's tender Impressionist classic: The Cradle (Musée d'Orsay).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-childs-bath",
        "title": "The Child's Bath",
        "original_title": "The Child's Bath",
        "artist": "Mary Cassatt",
        "year": "1893",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "100.3 cm × 66.1 cm",
        "location": "Art Institute of Chicago, United States",
        "query": "Mary Cassatt The Childs Bath Art Institute of Chicago",
        "description": "A mother tenderly washes her young child's feet in a small copper basin, draped in a bold striped dressing gown.",
        "analysis": "Combines French Impressionism with the compositional clarity and overhead bird's-eye perspective of Japanese woodblocks.",
        "featured": True,
        "instagram_post_caption": "Mary Cassatt's touch of maternal tenderness: The Child's Bath in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "portrait-of-madame-x",
        "title": "Portrait of Madame X",
        "original_title": "Madame Pierre Gautreau",
        "artist": "John Singer Sargent",
        "year": "1884",
        "period": "Realism / Aestheticism",
        "medium": "Oil on canvas",
        "dimensions": "208.6 cm × 109.9 cm",
        "location": "Metropolitan Museum of Art, New York, United States",
        "query": "John Singer Sargent Madame X Metropolitan Museum of Art",
        "description": "The American-born Parisian socialite Virginie Gautreau poses in profile in a plunging black satin gown with bejeweled straps against a warm umber background.",
        "analysis": "Caused a massive scandal at the 1884 Paris Salon due to its audacious sensuality; today regarded as Sargent's supreme portrait masterpiece.",
        "featured": True,
        "instagram_post_caption": "Sargent's scandalous tour de force: Portrait of Madame X (The Met).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "carnation-lily-lily-rose",
        "title": "Carnation, Lily, Lily, Rose",
        "original_title": "Carnation, Lily, Lily, Rose",
        "artist": "John Singer Sargent",
        "year": "1885–1886",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "174 cm × 153.7 cm",
        "location": "Tate Britain, London, United Kingdom",
        "query": "John Singer Sargent Carnation Lily Lily Rose Tate",
        "description": "Two young girls in white dresses light paper lanterns in an English country garden brimming with white lilies, pink roses, and yellow carnations at twilight.",
        "analysis": "Painted outdoors in fleeting moments of twilight (en plein air) to capture the magical glow of lanterns against lavender dusk.",
        "featured": False,
        "instagram_post_caption": "Sargent's enchanting twilight poetry: Carnation, Lily, Lily, Rose.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "breezing-up",
        "title": "Breezing Up (A Fair Wind)",
        "original_title": "Breezing Up (A Fair Wind)",
        "artist": "Winslow Homer",
        "year": "1873–1876",
        "period": "Realism",
        "medium": "Oil on canvas",
        "dimensions": "61.5 cm × 97 cm",
        "location": "National Gallery of Art, Washington, D.C., United States",
        "query": "Winslow Homer Breezing Up National Gallery of Art",
        "description": "A fisherman and three young boys steer a catboat across choppy sunlit waters in Gloucester, Massachusetts under a brisk sea breeze.",
        "analysis": "An enduring symbol of American youth, optimism, and maritime spirit painted during the nation's 1876 Centennial.",
        "featured": False,
        "instagram_post_caption": "Winslow Homer's American maritime classic: Breezing Up (A Fair Wind).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-gulf-stream",
        "title": "The Gulf Stream",
        "original_title": "The Gulf Stream",
        "artist": "Winslow Homer",
        "year": "1899",
        "period": "Realism",
        "medium": "Oil on canvas",
        "dimensions": "71.4 cm × 124.8 cm",
        "location": "Metropolitan Museum of Art, New York, United States",
        "query": "Winslow Homer The Gulf Stream Metropolitan Museum of Art",
        "description": "A solitary Black sailor adrift on a dismasted, rudderless boat in shark-infested Caribbean waters beneath a distant waterspout.",
        "analysis": "A dramatic confrontation between human vulnerability and elemental nature, rich with themes of mortality, endurance, and destiny.",
        "featured": True,
        "instagram_post_caption": "Winslow Homer's thrilling epic of survival: The Gulf Stream in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "washington-crossing-the-delaware",
        "title": "Washington Crossing the Delaware",
        "original_title": "Washington Crossing the Delaware",
        "artist": "Emanuel Leutze",
        "year": "1851",
        "period": "Romanticism / History Painting",
        "medium": "Oil on canvas",
        "dimensions": "378.5 cm × 647.7 cm",
        "location": "Metropolitan Museum of Art, New York, United States",
        "query": "Emanuel Leutze Washington Crossing the Delaware Metropolitan Museum of Art",
        "description": "General George Washington leads the Continental Army across the ice-choked Delaware River on Christmas night 1776 for a surprise attack on Trenton.",
        "analysis": "A monumental icon of American history painting, radiating heroic resolve, dramatic lighting, and theatrical national identity.",
        "featured": True,
        "instagram_post_caption": "Emanuel Leutze's epic American monument: Washington Crossing the Delaware.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-course-of-empire-destruction",
        "title": "The Course of Empire: Destruction",
        "original_title": "The Course of Empire: Destruction",
        "artist": "Thomas Cole",
        "year": "1836",
        "period": "Romanticism / Hudson River School",
        "medium": "Oil on canvas",
        "dimensions": "100 cm × 161 cm",
        "location": "New-York Historical Society, United States",
        "query": "Thomas Cole The Course of Empire Destruction",
        "description": "A colossal classical imperial city collapses into fire, war, and tempest as enemy fleets breach the harbor and bridges collapse.",
        "analysis": "The dramatic climax of Cole's five-part philosophical cycle, cautioning against imperial hubris, militarism, and moral decay.",
        "featured": False,
        "instagram_post_caption": "Thomas Cole's apocalyptic warning: The Course of Empire - Destruction.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-oxbow",
        "title": "The Oxbow",
        "original_title": "View from Mount Holyoke, Northampton, Massachusetts, after a Thunderstorm",
        "artist": "Thomas Cole",
        "year": "1836",
        "period": "Hudson River School / Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "130.8 cm × 193 cm",
        "location": "Metropolitan Museum of Art, New York, United States",
        "query": "Thomas Cole The Oxbow Metropolitan Museum of Art",
        "description": "A panoramic vista from Mount Holyoke contrasting untamed stormy wilderness on the left with cultivated sunlit farmland along the Connecticut River on the right.",
        "analysis": "The foundational masterpiece of the Hudson River School, meditating on the transformation of the American wilderness into civilization.",
        "featured": False,
        "instagram_post_caption": "Thomas Cole's grand American panorama: The Oxbow in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "isle-of-the-dead",
        "title": "Isle of the Dead",
        "original_title": "Die Toteninsel",
        "artist": "Arnold Böcklin",
        "year": "1883",
        "period": "Symbolism",
        "medium": "Oil on wood",
        "dimensions": "80 cm × 150 cm",
        "location": "Alte Nationalgalerie, Berlin, Germany",
        "query": "Arnold Bocklin Isle of the Dead Alte Nationalgalerie Berlin",
        "description": "A solitary shrouded white figure and coffin are ferried across dark glassy waters toward a fortress-like rocky island planted with towering cypress trees.",
        "analysis": "The supreme archetype of European Symbolist mystery and melancholy, creating an atmosphere of profound silence that inspired Freud, Rachmaninoff, and Dali.",
        "featured": True,
        "instagram_post_caption": "Arnold Böcklin's haunting vision of eternity: Isle of the Dead (Die Toteninsel).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-nightmare",
        "title": "The Nightmare",
        "original_title": "The Nightmare",
        "artist": "Henry Fuseli",
        "year": "1781",
        "period": "Romanticism / Gothic",
        "medium": "Oil on canvas",
        "dimensions": "101.6 cm × 127 cm",
        "location": "Detroit Institute of Arts, United States",
        "query": "Henry Fuseli The Nightmare Detroit Institute of Arts",
        "description": "A demonic incubus crouches menacingly atop a slumbering woman draped across a bed as a ghostly spectral horse peers through the velvet curtains.",
        "analysis": "A foundational landmark of Gothic Romanticism and the subconscious, visualizing human erotic vulnerability and nightmare terror.",
        "featured": False,
        "instagram_post_caption": "Henry Fuseli's Gothic psychological shockwave: The Nightmare in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "judith-and-the-head-of-holofernes",
        "title": "Judith and the Head of Holofernes",
        "original_title": "Judith I",
        "artist": "Gustav Klimt",
        "year": "1901",
        "period": "Art Nouveau / Symbolism",
        "medium": "Oil and gold leaf on canvas",
        "dimensions": "84 cm × 42 cm",
        "location": "Belvedere, Vienna, Austria",
        "query": "Gustav Klimt Judith I Belvedere Vienna",
        "description": "A sensual Viennese femme fatale in a jeweled gold choker holds the severed head of Holofernes against a shimmering gilded background.",
        "analysis": "Pioneered Klimt's legendary Golden Phase, fusing biblical drama with Viennese Secession decadence and erotic magnetism.",
        "featured": True,
        "instagram_post_caption": "Klimt's golden seduction: Judith I in Ultra HD (Belvedere Museum).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "lady-with-a-fan",
        "title": "Lady with a Fan",
        "original_title": "Dame mit Fächer",
        "artist": "Gustav Klimt",
        "year": "1917–1918",
        "period": "Art Nouveau / Vienna Secession",
        "medium": "Oil on canvas",
        "dimensions": "100 cm × 100 cm",
        "location": "Private Collection (Sold at Sotheby's London)",
        "query": "Gustav Klimt Lady with a Fan Dame mit Facher",
        "description": "A beautiful young woman holds a folded fan, surrounded by vibrant East Asian motifs of flying phoenixes and lotus blossoms.",
        "analysis": "Klimt's final completed masterpiece before his death, showcasing incandescent turquoise, canary yellow, and Japanese Japonisme aesthetics.",
        "featured": False,
        "instagram_post_caption": "Gustav Klimt's glowing final masterpiece: Lady with a Fan.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-death-of-socrates",
        "title": "The Death of Socrates",
        "original_title": "La Mort de Socrate",
        "artist": "Jacques-Louis David",
        "year": "1787",
        "period": "Neoclassicism",
        "medium": "Oil on canvas",
        "dimensions": "129.5 cm × 196.2 cm",
        "location": "Metropolitan Museum of Art, New York, United States",
        "query": "Jacques-Louis David The Death of Socrates Metropolitan Museum of Art",
        "description": "The philosopher Socrates sits upright on his prison bed calmly reaching for a cup of hemlock poison while lecturing his grieving disciples.",
        "analysis": "A quintessential masterpiece of Neoclassical geometric rigor, stoicism, and intellectual courage on the eve of the French Revolution.",
        "featured": True,
        "instagram_post_caption": "Jacques-Louis David's Neoclassical moral triumph: The Death of Socrates.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "oath-of-the-horatii",
        "title": "Oath of the Horatii",
        "original_title": "Le Serment des Horaces",
        "artist": "Jacques-Louis David",
        "year": "1784",
        "period": "Neoclassicism",
        "medium": "Oil on canvas",
        "dimensions": "329.8 cm × 424.8 cm",
        "location": "Musée du Louvre, Paris, France",
        "query": "Jacques-Louis David Oath of the Horatii Louvre",
        "description": "Three Roman brothers swear an oath on their father's swords to defend the Roman Republic against the Curiatii of Alba Longa.",
        "analysis": "The defining manifesto of Neoclassicism, emphasizing civic duty, patriotism, and heroic self-sacrifice over personal grief.",
        "featured": False,
        "instagram_post_caption": "David's revolutionary manifesto of Roman duty: Oath of the Horatii.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-grand-odalisque",
        "title": "The Grand Odalisque",
        "original_title": "La Grande Odalisque",
        "artist": "Jean-Auguste-Dominique Ingres",
        "year": "1814",
        "period": "Neoclassicism / Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "91 cm × 162 cm",
        "location": "Musée du Louvre, Paris, France",
        "query": "Jean-Auguste-Dominique Ingres La Grande Odalisque Louvre",
        "description": "A concubine reclines in a luxurious orientalist interior on blue silk cushions holding a peacock fan and looking over her shoulder.",
        "analysis": "Celebrated for its languid elongated spine, serpentine curvilinear grace, and exquisite textural rendering of silk and pearls.",
        "featured": True,
        "instagram_post_caption": "Ingres's sensual perfection of line: La Grande Odalisque (Musée du Louvre).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-source",
        "title": "The Source",
        "original_title": "La Source",
        "artist": "Jean-Auguste-Dominique Ingres",
        "year": "1856",
        "period": "Neoclassicism",
        "medium": "Oil on canvas",
        "dimensions": "163 cm × 80 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Jean-Auguste-Dominique Ingres La Source Musee dOrsay",
        "description": "A classical female nude stands between rock walls pouring pure spring water from a heavy earthenware jug on her shoulder.",
        "analysis": "The epitome of Ingres's lifelong pursuit of ideal anatomical beauty, pure contour lines, and crystalline neoclassical clarity.",
        "featured": False,
        "instagram_post_caption": "Ingres's serene embodiment of purity: La Source in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "massacre-at-chios",
        "title": "The Massacre at Chios",
        "original_title": "Scène des massacres de Scio",
        "artist": "Eugène Delacroix",
        "year": "1824",
        "period": "Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "419 cm × 354 cm",
        "location": "Musée du Louvre, Paris, France",
        "query": "Eugene Delacroix The Massacre at Chios Louvre",
        "description": "The tragic devastation of Greek civilians by Ottoman forces on the island of Chios during the Greek War of Independence.",
        "analysis": "Delacroix broke completely with classical balance, creating a visceral Romantic epic of human suffering, swirling color, and raw empathy.",
        "featured": False,
        "instagram_post_caption": "Delacroix's impassioned Romantic monument: The Massacre at Chios.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-death-of-sardanapalus",
        "title": "The Death of Sardanapalus",
        "original_title": "La Mort de Sardanapale",
        "artist": "Eugène Delacroix",
        "year": "1827",
        "period": "Romanticism",
        "medium": "Oil on canvas",
        "dimensions": "392 cm × 496 cm",
        "location": "Musée du Louvre, Paris, France",
        "query": "Eugene Delacroix La Mort de Sardanapale Louvre",
        "description": "The besieged Assyrian King Sardanapalus lounges indifferently on a massive red bed as his treasures, horses, and concubines are slaughtered around him.",
        "analysis": "A whirlwind of orientalist decadence, turbulent diagonal brushwork, and saturated crimson pigment that electrified French Romanticism.",
        "featured": False,
        "instagram_post_caption": "Delacroix's intoxicating spectacle of destruction: The Death of Sardanapalus.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-triumph-of-bacchus",
        "title": "The Triumph of Bacchus",
        "original_title": "El triunfo de Baco (Los borrachos)",
        "artist": "Diego Velázquez",
        "year": "1628–1629",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "165 cm × 188 cm",
        "location": "Museo del Prado, Madrid, Spain",
        "query": "Diego Velazquez El triunfo de Baco Los borrachos Prado",
        "description": "Bacchus, god of wine, sits with sunburnt Spanish peasants crowning a soldier with vine leaves while a rustic reveler smiles roguishly at the viewer.",
        "analysis": "Brilliantly humanizes classical mythology with the earthy realism of Castilian tavern life and luminous natural flesh tones.",
        "featured": False,
        "instagram_post_caption": "Velázquez's earthy myth of wine and camaraderie: Los Borrachos (El Prado).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "lady-agnew-of-lochnaw",
        "title": "Lady Agnew of Lochnaw",
        "original_title": "Lady Agnew of Lochnaw",
        "artist": "John Singer Sargent",
        "year": "1892",
        "period": "Realism / Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "127 cm × 101 cm",
        "location": "Scottish National Gallery, Edinburgh, United Kingdom",
        "query": "John Singer Sargent Lady Agnew of Lochnaw Scottish National Gallery",
        "description": "Gertrude Vernon, Lady Agnew, reclines comfortably in a French bergère chair draped in white silk and a mauve silk sash, meeting the viewer with an intimate smile.",
        "analysis": "Established Sargent's international renown as the finest society portraitist of the Gilded Age through effortless fluid brushstrokes and luminous fabrics.",
        "featured": False,
        "instagram_post_caption": "Sargent's peerless portrait perfection: Lady Agnew of Lochnaw in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-clothed-mrs-fisk",
        "title": "The Japanese Bridge",
        "original_title": "Le Pont japonais",
        "artist": "Claude Monet",
        "year": "1899",
        "period": "Impressionism",
        "medium": "Oil on canvas",
        "dimensions": "92.7 cm × 73.7 cm",
        "location": "National Gallery of Art, Washington, D.C., United States",
        "query": "Claude Monet The Japanese Footbridge National Gallery of Art",
        "description": "The green wooden footbridge arches over the water lily pond at Giverny, surrounded by weeping willows, reeds, and glowing reflections.",
        "analysis": "Monet's quintessential garden symphony, capturing shimmering light filters and layered water reflections in harmonious greens and blues.",
        "featured": True,
        "instagram_post_caption": "Monet's idyllic paradise in Giverny: The Japanese Footbridge.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "saint-jerome-writing",
        "title": "Saint Jerome Writing",
        "original_title": "San Girolamo scrivente",
        "artist": "Caravaggio",
        "year": "1605–1606",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "112 cm × 157 cm",
        "location": "Galleria Borghese, Rome, Italy",
        "query": "Caravaggio Saint Jerome Writing Galleria Borghese",
        "description": "An elderly Saint Jerome in a crimson drape reaches his quill across a table with a skull memento mori while translating the Bible into Latin.",
        "analysis": "A supreme study of scholarly concentration and mortality, contrasting the aged saint's weathered flesh with bright directional lighting.",
        "featured": False,
        "instagram_post_caption": "Caravaggio's quiet monument of faith and scholarship: Saint Jerome Writing.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-art-of-painting",
        "title": "The Art of Painting",
        "original_title": "De schilderkunst",
        "artist": "Johannes Vermeer",
        "year": "c. 1666–1668",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "120 cm × 100 cm",
        "location": "Kunsthistorisches Museum, Vienna, Austria",
        "query": "Johannes Vermeer The Art of Painting Kunsthistorisches Museum",
        "description": "An artist in elegant historical dress paints Clio, the muse of history, before an ornate wall map of the Seventeen Dutch Provinces.",
        "analysis": "Vermeer's most ambitious allegory and personal pride, celebrating the nobility of painting and Dutch historical heritage.",
        "featured": True,
        "instagram_post_caption": "Vermeer's ultimate testament to art: The Art of Painting (Vienna).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-two-fridas",
        "title": "The Arnolfini Portrait Mirror Detail",
        "original_title": "The Madonna of Chancellor Rolin",
        "artist": "Jan van Eyck",
        "year": "c. 1435",
        "period": "Northern Renaissance",
        "medium": "Oil on wood",
        "dimensions": "66 cm × 62 cm",
        "location": "Musée du Louvre, Paris, France",
        "query": "Jan van Eyck The Virgin of Chancellor Rolin Louvre",
        "description": "Nicolas Rolin, Chancellor of Burgundy, kneels in prayer opposite the Virgin Mary holding the Christ Child before a panoramic medieval city.",
        "analysis": "Van Eyck's peerless microscopic oil glazing technique, rendering marble tiles, stained glass, and distant bridges with astonishing realism.",
        "featured": False,
        "instagram_post_caption": "Jan van Eyck's diamond-sharp Renaissance jewel: Madonna of Chancellor Rolin.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "danseuse-sur-la-scene",
        "title": "Ballet Dancer on Stage",
        "original_title": "Danseuse sur la scène",
        "artist": "Edgar Degas",
        "year": "c. 1878",
        "period": "Impressionism",
        "medium": "Pastel on paper",
        "dimensions": "58 cm × 42 cm",
        "location": "Musée d'Orsay, Paris, France",
        "query": "Edgar Degas Danseuse sur la scene Musee dOrsay",
        "description": "A ballerina pauses mid-pirouette under the luminous footlights of the Paris Opera stage while shadowy patrons watch from the wings.",
        "analysis": "Degas's virtuoso handling of pastel, blending vibrant glowing stage illumination with the airy weightlessness of white tulle.",
        "featured": False,
        "instagram_post_caption": "Degas's magical stage illumination: Ballet Dancer on Stage in Ultra HD.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-beheading-of-saint-john-the-baptist",
        "title": "The Beheading of Saint John the Baptist",
        "original_title": "Decollazione di San Giovanni Battista",
        "artist": "Caravaggio",
        "year": "1608",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "361 cm × 520 cm",
        "location": "St. John's Co-Cathedral, Valletta, Malta",
        "query": "Caravaggio The Beheading of Saint John the Baptist Malta",
        "description": "The executioner prepares to deliver the final strike to Saint John the Baptist in a bleak Maltese prison courtyard as Salome holds a golden platter.",
        "analysis": "Caravaggio's largest painting and only signed work, created with immense psychological gravity and dramatic negative space.",
        "featured": True,
        "instagram_post_caption": "Caravaggio's monumental Maltese masterpiece: The Beheading of Saint John.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-jewish-bride",
        "title": "The Jewish Bride",
        "original_title": "Het Joodse bruidje",
        "artist": "Rembrandt van Rijn",
        "year": "c. 1665–1669",
        "period": "Baroque",
        "medium": "Oil on canvas",
        "dimensions": "121.5 cm × 166.5 cm",
        "location": "Rijksmuseum, Amsterdam, Netherlands",
        "query": "Rembrandt The Jewish Bride Rijksmuseum",
        "description": "A man places his hand tenderly over the heart of a young woman dressed in glowing red silk in an intimate gesture of marital devotion.",
        "analysis": "A transcendent pinnacle of Rembrandt's late style, renowned for its heavy sculptural golden impasto and profound emotional warmth.",
        "featured": False,
        "instagram_post_caption": "Rembrandt's most tender portrait of love: The Jewish Bride (Rijksmuseum).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "the-death-of-general-wolfe",
        "title": "The Death of General Wolfe",
        "original_title": "The Death of General Wolfe",
        "artist": "Benjamin West",
        "year": "1770",
        "period": "Neoclassicism / History Painting",
        "medium": "Oil on canvas",
        "dimensions": "151 cm × 213 cm",
        "location": "National Gallery of Canada, Ottawa",
        "query": "Benjamin West The Death of General Wolfe National Gallery of Canada",
        "description": "British General James Wolfe dies in the arms of his officers on the Plains of Abraham during the Battle of Quebec in 1759.",
        "analysis": "Revolutionized history painting by clothing modern historical figures in realistic contemporary uniforms rather than classical Roman togas.",
        "featured": False,
        "instagram_post_caption": "Benjamin West's dramatic milestone of history painting: The Death of General Wolfe.",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    },
    {
        "slug": "madame-recamier",
        "title": "Portrait of Madame Récamier",
        "original_title": "Madame Récamier",
        "artist": "Jacques-Louis David",
        "year": "1800",
        "period": "Neoclassicism",
        "medium": "Oil on canvas",
        "dimensions": "174 cm × 244 cm",
        "location": "Musée du Louvre, Paris, France",
        "query": "Jacques-Louis David Portrait of Madame Recamier Louvre",
        "description": "The Parisian salon socialite Juliette Récamier reclines barefoot in an empire-style white dress on a classical chaise longue.",
        "analysis": "Left intentionally unfinished by David, celebrated for its severe neoclassical minimalism, delicate line work, and quiet elegance.",
        "featured": False,
        "instagram_post_caption": "Jacques-Louis David's neoclassical elegance: Madame Récamier (Louvre).",
        "instagram_tag": "@classicartarchive",
        "license": "Public Domain (CC0 / PDM 1.0)"
    }
]


def find_commons_image(query: str, fallback_title: str = "") -> str:
    search_queries = [query]
    if fallback_title and fallback_title != query:
        search_queries.append(fallback_title)
        
    for q in search_queries:
        try:
            url = f"https://commons.wikimedia.org/w/api.php?action=query&list=search&srnamespace=6&srsearch={urllib.parse.quote(q)}&format=json"
            req = urllib.request.Request(url, headers=HEADERS)
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read().decode("utf-8"))
            results = data.get("query", {}).get("search", [])
            if not results:
                continue
            title = results[0]["title"]
            
            info_url = f"https://commons.wikimedia.org/w/api.php?action=query&titles={urllib.parse.quote(title)}&prop=imageinfo&iiprop=url|size&iiurlwidth=4000&format=json"
            req2 = urllib.request.Request(info_url, headers=HEADERS)
            with urllib.request.urlopen(req2, timeout=15) as resp:
                info_data = json.loads(resp.read().decode("utf-8"))
            pages = info_data.get("query", {}).get("pages", {})
            for p in pages.values():
                for info in p.get("imageinfo", []):
                    orig_size = info.get("size", 0)
                    orig_url = info.get("url")
                    thumb_url = info.get("thumburl")
                    if orig_size < 35_000_000 and orig_url:
                        return orig_url
                    if thumb_url:
                        return thumb_url
                    if orig_url:
                        return orig_url
        except Exception as e:
            print(f"    [Search Error for '{q}']: {e}")
            time.sleep(1)
    return ""


# Load existing 30 artworks
with open(DATA_FILE, "r", encoding="utf-8") as f:
    existing_artworks = json.load(f)

existing_slugs = {a["slug"] for a in existing_artworks}
print(f"Current archive has {len(existing_artworks)} artworks.")

processed_count = len(existing_artworks)

for idx, item in enumerate(artworks_31_to_100, 1):
    slug = item["slug"]
    title = item["title"]
    artist = item["artist"]
    
    if slug in existing_slugs:
        print(f"[{idx}/70] Skipping already existing '{slug}'")
        continue
        
    master_file = MASTERS_DIR / f"{slug}.jpg"
    thumb_file = ARTWORKS_DIR / f"{slug}.jpg"
    
    print(f"\n[{idx}/70] Resolving & downloading: {title} by {artist} ({slug})...", flush=True)
    
    img_url = find_commons_image(item.get("query", f"{artist} {title}"), f"{title} {artist}")
    if not img_url:
        print(f"  -> WARNING: Could not find image for {title}!")
        continue
        
    print(f"  -> Found image URL: {img_url[:80]}...", flush=True)
    
    download_ok = False
    for attempt in range(3):
        try:
            time.sleep(0.8)
            req = urllib.request.Request(img_url, headers=HEADERS)
            with urllib.request.urlopen(req, timeout=45) as resp:
                data = resp.read()
                
            img = Image.open(io.BytesIO(data))
            if img.mode in ("RGBA", "P"):
                img = img.convert("RGB")
                
            w, h = img.size
            max_side = 5000
            if max(w, h) > max_side:
                ratio = max_side / max(w, h)
                img = img.resize((int(w * ratio), int(h * ratio)), Image.Resampling.LANCZOS)
                
            img.save(master_file, "JPEG", quality=94, optimize=True)
            master_mb = master_file.stat().st_size / (1024 * 1024)
            final_w, final_h = img.size
            
            web_max = 1600
            if max(final_w, final_h) > web_max:
                ratio_web = web_max / max(final_w, final_h)
                web_img = img.resize((int(final_w * ratio_web), int(final_h * ratio_web)), Image.Resampling.LANCZOS)
                web_img.save(thumb_file, "JPEG", quality=88, optimize=True)
            else:
                img.save(thumb_file, "JPEG", quality=88, optimize=True)
                
            processed_count += 1
            entry = {
                "id": processed_count,
                "slug": slug,
                "title": title,
                "original_title": item.get("original_title", title),
                "artist": artist,
                "year": item.get("year", "Classic Era"),
                "period": item.get("period", "Classic"),
                "medium": item.get("medium", "Oil on canvas"),
                "dimensions": item.get("dimensions", "Standard"),
                "location": item.get("location", "Museum Collection"),
                "image_url": img_url,
                "thumbnail_url": f"/static/img/artworks/{slug}.jpg",
                "download_filename": f"{artist.split()[-1]}_{slug.replace('-', '_').title()}_UltraHD.jpg",
                "resolution": f"{final_w:,} × {final_h:,} px".replace(",", " "),
                "file_size": f"{master_mb:.1f} MB",
                "description": item.get("description", ""),
                "analysis": item.get("analysis", ""),
                "featured": item.get("featured", False),
                "instagram_post_caption": item.get("instagram_post_caption", f"{title} by {artist}"),
                "instagram_tag": "@classicartarchive",
                "license": "Public Domain (CC0 / PDM 1.0)"
            }
            
            existing_artworks.append(entry)
            existing_slugs.add(slug)
            
            # Save progress incrementally to artworks.json
            with open(DATA_FILE, "w", encoding="utf-8") as f:
                json.dump(existing_artworks, f, indent=2, ensure_ascii=False)
                
            print(f"  -> Successfully saved #{processed_count}: {title} ({final_w}x{final_h}, {master_mb:.1f} MB)", flush=True)
            download_ok = True
            break
        except Exception as e:
            print(f"  -> Attempt {attempt+1} failed: {e}", flush=True)
            time.sleep(2)

print(f"\n=======================================================")
print(f"BATCH FINISHED! Total artworks in database: {len(existing_artworks)}")
print(f"=======================================================")
